name: CI/Build

on:
  
  push:
    branches: [ armv7 ]
  workflow_dispatch:

env:
  DOTNET_SDK_VERSION: "8.0.*"

jobs:

  build-linux-armv7:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm64-20220312201346-b2c2436

    steps:
      - uses: actions/checkout@v1
      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - run: dotnet publish src/N_m3u8DL-RE -r linux-arm -c Release -p:StripSymbols=true -p:CppCompilerAndLinker=clang-9 -p:SysRoot=/crossrootfs/arm32 -o artifact

      - name: Upload Artifact[linux-arm64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: N_m3u8DL-RE_Beta_linux-arm64
          path: artifact/N_m3u8DL-RE

